### ISSUE TITLE
Readme Specifies Non-Optimal CsProj property for Dynamic Loading

### ISSUE THREAD

**Issue by Sewer56** [SnowflakePowered/sabinokaku#1]
In short: 

In the usage section of your library, you specify the usage of the `GenerateRuntimeConfigurationFiles` to ensure that loadable assemblies are created. While this works, the advised property to set for end users is instead [`EnableDynamicLoading` property](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enabledynamicloading).

![vivaldi_zy6XQyuCOA](https://user-images.githubusercontent.com/6697380/153721627-a916614f-3d28-477f-a30f-094d5455375d.png)

Or to quote Mr Vitek Karas, one of the .NET Runtime developers.

> In the readme for this project there's a section about troubleshooting - specifically the case of a classlib which doesn't have `.runtimeconfig.json` by default. Starting with recent .NET Core 3.0 previews (8 for sure, probably earlier) the right way to mark a classlib as a component which will be dynamically loaded is to add `<EnableDynamicLoading>true</EnableDynamicLoading>` to the project.

> Under the hood it does currently set the `GenerateRuntimeConfigurationFiles` but this may change in the future.

([original text](https://github.com/Reloaded-Project/Reloaded.Core.Bootstrap/issues/1))

A few years ago I made the same mistake too, albeit all of the new properties weren't yet fully documented then.

**Comment by chyyran** [comment]
Thanks for pointing this out. Fixed in https://github.com/SnowflakePowered/sabinokaku/commit/0a6bf7897f43aa144b68cde38fdc555a76923cf4
